import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-timber-stumpage-royalty-audit",
  "engine": "recovery",
  "title": "Timber Stumpage Royalty Audit",
  "shortTitle": "Timber Stumpage Royalty Audit",
  "tagline": "Reconstruct harvested volume and contract pricing to recover underreported timber and unsupported deductions.",
  "industry": "Natural Resources Revenue Assurance",
  "buyer": "Timberland owners and investment managers",
  "uiPort": 4711,
  "apiPort": 5711,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Timber Stumpage Royalty Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments in one accountable workflow. Reconstruct harvested volume and contract pricing to recover underreported timber and unsupported deductions.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Timber Stumpage Royalty Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("stumpage-agreement-library","TSR01","Stumpage agreement library","Execute stumpage agreement library using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed stumpage agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Stumpage agreement library Reference","text","TSR01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("tract-cruise-inventory","TSR02","Tract cruise inventory","Execute tract cruise inventory using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed tract cruise inventory decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Tract cruise inventory Reference","text","TSR02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("species-grade-mapping","TSR03","Species grade mapping","Execute species grade mapping using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed species grade mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Species grade mapping Reference","text","TSR03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("harvest-load-ingestion","TSR04","Harvest load ingestion","Execute harvest load ingestion using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed harvest load ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Harvest load ingestion Reference","text","TSR04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("scale-ticket-validation","TSR05","Scale ticket validation","Execute scale ticket validation using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed scale ticket validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Scale ticket validation Reference","text","TSR05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("mill-receipt-matching","TSR06","Mill receipt matching","Execute mill receipt matching using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed mill receipt matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Mill receipt matching Reference","text","TSR06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("weight-conversion-factors","TSR07","Weight conversion factors","Execute weight conversion factors using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed weight conversion factors decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Weight conversion factors Reference","text","TSR07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("board-foot-calculation","TSR08","Board-foot calculation","Execute board-foot calculation using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed board-foot calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Board-foot calculation Reference","text","TSR08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("index-price-validation","TSR09","Index price validation","Execute index price validation using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed index price validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Index price validation Reference","text","TSR09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("hauling-deduction-audit","TSR10","Hauling deduction audit","Execute hauling deduction audit using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed hauling deduction audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Hauling deduction audit Reference","text","TSR10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("road-cost-deduction","TSR11","Road cost deduction","Execute road cost deduction using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed road cost deduction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Road cost deduction Reference","text","TSR11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("settlement-recalculation","TSR12","Settlement recalculation","Execute settlement recalculation using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed settlement recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Settlement recalculation Reference","text","TSR12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("logger-mill-dispute-workflow","TSR13","Logger mill dispute workflow","Execute logger mill dispute workflow using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed logger mill dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Logger mill dispute workflow Reference","text","TSR13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("cash-reconciliation","TSR14","Cash reconciliation","Execute cash reconciliation using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Cash reconciliation Reference","text","TSR14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]}),
feature("tract-species-analytics","TSR15","Tract species analytics","Execute tract species analytics using stumpage agreements, tract cruises, species, grades, scale tickets, mill receipts, indexes, deductions, settlements, and payments.","Produce a governed tract species analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Logger / Timber Tract","text","Logger / Timber Tract · Standard Case"],["caseReference","Tract species analytics Reference","text","TSR15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1442500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1745425],["domainDriver","Scale Method","select","Weight scale",["Weight scale","Board-foot scale","Cord scale"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Stumpage agreement library case","Tract cruise inventory case","Species grade mapping case","Harvest load ingestion case","Scale ticket validation case"]})
]);
